# Generated by Django 2.2.5 on 2019-10-01 00:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0015_auto_20191001_0551'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Invoice')),
            ],
        ),
    ]
