# Generated by Django 2.2.5 on 2019-10-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20191001_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
