# Generated by Django 2.2.5 on 2019-10-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payments_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
