# Generated by Django 2.2.5 on 2019-09-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190925_0933'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price_per_product', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.SupplierProductInfo')),
            ],
        ),
    ]
