# Generated by Django 2.2.5 on 2019-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190928_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Supplier',
            field=models.BooleanField(default=False),
        ),
    ]
