# Generated by Django 2.2.5 on 2019-09-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_type', models.CharField(max_length=100)),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Qty', models.IntegerField()),
                ('Amount', models.CharField(max_length=50)),
                ('Order_date', models.DateTimeField(auto_now=True)),
                ('Status', models.CharField(choices=[('Available', 'Available'), ('Less amount of Stock', 'Less Amount of Stock'), ('Out Of Stock', 'Out of Stock')], default='Available', max_length=50)),
            ],
        ),
    ]
