# Generated by Django 2.2.5 on 2019-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproductinfo',
            name='Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Less amount of Stock', 'Less Amount of Stock'), ('Out Of Stock', 'Out of Stock')], default='Available', max_length=50),
        ),
    ]
