# Generated by Django 2.2.5 on 2019-09-25 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_supplier'),
        ('supplier', '0002_auto_20190925_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproductinfo',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='supplierproductinfo',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='supplierproductinfo',
            name='Product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductType'),
        ),
    ]
