# Generated by Django 2.2.5 on 2019-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='defalts', max_length=255),
            preserve_default=False,
        ),
    ]
