# Generated by Django 2.2.5 on 2019-09-30 17:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('amount_due', models.FloatField()),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('NOT', 'NOT'), ('Pending', 'Pending')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('product', models.ManyToManyField(to='product.ProductOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed')], max_length=50)),
                ('approval', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('NOT', 'NOT')], default='Approved', max_length=50)),
                ('product_and_quantity', models.ManyToManyField(to='order.Tender')),
            ],
        ),
    ]
