# Generated by Django 2.2.5 on 2019-09-27 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductType')),
            ],
        ),
    ]
