# Generated by Django 2.2.5 on 2019-09-30 06:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('product', models.ManyToManyField(to='product.ProductOrder')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('amount', models.FloatField()),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed')], max_length=50)),
                ('product', models.ManyToManyField(to='order.Tender')),
            ],
        ),
    ]
