# Generated by Django 2.2.5 on 2019-09-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('order', '0003_orderrequest_product_orderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
