# Generated by Django 2.2.5 on 2019-09-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_tender_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_and_quantity',
            field=models.ManyToManyField(blank=True, to='order.Tender'),
        ),
    ]
