# Generated by Django 2.2.5 on 2019-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191001_0242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approval',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('NOT', 'NOT')], max_length=50),
        ),
    ]
