# Generated by Django 2.2.5 on 2019-09-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('order', '0007_auto_20191001_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
