# Generated by Django 2.2.5 on 2019-09-30 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191001_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='site',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
