# Generated by Django 2.2.5 on 2019-09-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191001_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
