# Generated by Django 2.2.5 on 2019-09-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20191001_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
