# Generated by Django 2.2.5 on 2019-10-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20191001_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.SupplierProductInfo'),
        ),
    ]
