# Generated by Django 2.2.5 on 2019-10-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('order', '0015_auto_20191001_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Payments'),
        ),
    ]
